create extension if not exists "pgcrypto" with schema "extensions";

create table if not exists "public"."profiles" (
    "id" uuid not null references "auth"."users" on delete cascade,
    "username" text not null,
    "role" text not null default 'funcionario'::text check (role in ('funcionario', 'gerente', 'admin_seguranca')),
    "nome" text not null,
    "email" text,
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now(),
    constraint "profiles_pkey" primary key ("id"),
    constraint "profiles_username_key" unique ("username")
);

create table if not exists "public"."resources" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "type" text not null check (type in ('equipamento', 'veiculo', 'dispositivo_seguranca')),
    "serial_number" text,
    "plate" text,
    "location" text not null,
    "status" text not null default 'disponivel'::text check (status in ('disponivel', 'em_uso', 'em_manutencao')),
    "acquisition_date" date not null,
    "last_maintenance_date" date,
    "created_by" uuid references "public"."profiles"("id") on delete set null,
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now(),
    "deleted_at" timestamptz,
    constraint "resources_pkey" primary key ("id")
);

create table if not exists "public"."service_orders" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "resource_id" bigint references "public"."resources"("id") on delete set null,
    "assigned_to" uuid references "public"."profiles"("id") on delete set null,
    "priority" text not null default 'media'::text check (priority in ('baixa', 'media', 'alta', 'urgente')),
    "status" text not null default 'aberta'::text check (status in ('aberta', 'em_andamento', 'concluida', 'cancelada')),
    "created_by" uuid references "public"."profiles"("id") on delete set null,
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now(),
    constraint "service_orders_pkey" primary key ("id")
);

create table if not exists "public"."maintenance_history" (
    "id" bigint generated by default as identity not null,
    "resource_id" bigint not null references "public"."resources"("id") on delete cascade,
    "description" text not null,
    "performed_by" text,
    "maintenance_date" date not null default current_date,
    "cost" numeric(10,2),
    "created_at" timestamptz not null default now(),
    constraint "maintenance_history_pkey" primary key ("id")
);

create table if not exists "public"."access_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid references "auth"."users"("id") on delete set null,
    "access_area" text not null,
    "access_time" timestamptz not null default now(),
    "status" text not null default 'sucesso'::text check (status in ('sucesso', 'falha')),
    "ip_address" text,
    constraint "access_logs_pkey" primary key ("id")
);

create table if not exists "public"."audit_logs" (
    "id" bigint generated by default as identity not null,
    "org_id" text,
    "user_id" uuid references "auth"."users"("id") on delete set null,
    "action" text not null,
    "entity" text not null,
    "entity_id" text,
    "old_data" jsonb,
    "new_data" jsonb,
    "ip_address" text,
    "created_at" timestamptz not null default now(),
    constraint "audit_logs_pkey" primary key ("id")
);

alter table "public"."profiles" enable row level security;
alter table "public"."resources" enable row level security;
alter table "public"."service_orders" enable row level security;
alter table "public"."maintenance_history" enable row level security;
alter table "public"."access_logs" enable row level security;
alter table "public"."audit_logs" enable row level security;

create policy "profiles_select_policy" on "public"."profiles" for select using (true);
create policy "profiles_insert_policy" on "public"."profiles" for insert with check (auth.uid() = id);
create policy "profiles_update_policy" on "public"."profiles" for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles_delete_policy" on "public"."profiles" for delete using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);

create policy "resources_select_policy" on "public"."resources" for select using (deleted_at is null);
create policy "resources_insert_policy" on "public"."resources" for insert with check (auth.role() = 'authenticated');
create policy "resources_update_policy" on "public"."resources" for update using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role in ('admin_seguranca', 'gerente'))
);
create policy "resources_delete_policy" on "public"."resources" for delete using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);

create policy "service_orders_select_policy" on "public"."service_orders" for select using (true);
create policy "service_orders_insert_policy" on "public"."service_orders" for insert with check (auth.role() = 'authenticated');
create policy "service_orders_update_policy" on "public"."service_orders" for update using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role in ('admin_seguranca', 'gerente'))
);
create policy "service_orders_delete_policy" on "public"."service_orders" for delete using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);

create policy "maintenance_history_select_policy" on "public"."maintenance_history" for select using (true);
create policy "maintenance_history_insert_policy" on "public"."maintenance_history" for insert with check (auth.role() = 'authenticated');
create policy "maintenance_history_update_policy" on "public"."maintenance_history" for update using (false);
create policy "maintenance_history_delete_policy" on "public"."maintenance_history" for delete using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);

create policy "access_logs_select_policy" on "public"."access_logs" for select using (true);
create policy "access_logs_insert_policy" on "public"."access_logs" for insert with check (auth.role() = 'authenticated');
create policy "access_logs_delete_policy" on "public"."access_logs" for delete using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);

create policy "audit_logs_select_policy" on "public"."audit_logs" for select using (
    exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca')
);
create policy "audit_logs_insert_policy" on "public"."audit_logs" for insert with check (auth.role() = 'authenticated');
create policy "audit_logs_update_policy" on "public"."audit_logs" for update using (false);
create policy "audit_logs_delete_policy" on "public"."audit_logs" for delete using (false);

create index if not exists "profiles_role_idx" on "public"."profiles" ("role");
create index if not exists "resources_type_idx" on "public"."resources" ("type");
create index if not exists "resources_status_idx" on "public"."resources" ("status");
create index if not exists "resources_deleted_at_idx" on "public"."resources" ("deleted_at");
create index if not exists "resources_created_by_idx" on "public"."resources" ("created_by");
create index if not exists "service_orders_status_idx" on "public"."service_orders" ("status");
create index if not exists "service_orders_assigned_to_idx" on "public"."service_orders" ("assigned_to");
create index if not exists "maintenance_history_resource_id_idx" on "public"."maintenance_history" ("resource_id");
create index if not exists "access_logs_user_id_idx" on "public"."access_logs" ("user_id");
create index if not exists "access_logs_access_time_idx" on "public"."access_logs" ("access_time");
create index if not exists "audit_logs_entity_idx" on "public"."audit_logs" ("entity");
create index if not exists "audit_logs_created_at_idx" on "public"."audit_logs" ("created_at");

create or replace function "public"."handle_new_user"()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
    insert into "public"."profiles" (id, username, role, nome, email)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substr(new.id::text, 1, 8)),
        coalesce(new.raw_user_meta_data ->> 'role', 'funcionario'),
        coalesce(new.raw_user_meta_data ->> 'nome', 'Usuario'),
        new.email
    );
    return new;
end;
$$;

create or replace function "public"."admin_delete_user"(user_id uuid)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
    if not exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca') then
        raise exception 'Apenas admin_seguranca pode excluir usuarios';
    end if;
    delete from "auth"."users" where id = user_id;
end;
$$;

create or replace function "public"."delete_old_logs"(days integer)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
    if not exists (select 1 from "public"."profiles" where id = auth.uid() and role = 'admin_seguranca') then
        raise exception 'Apenas admin_seguranca pode limpar logs';
    end if;
    delete from "public"."access_logs" where access_time < now() - (days || ' days')::interval;
end;
$$;

drop trigger if exists "on_auth_user_created" on "auth"."users";
create trigger "on_auth_user_created"
    after insert on "auth"."users"
    for each row
    execute function "public"."handle_new_user"();
